apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: dks-eks-ms
  type: core.Directory
  children:

  - name: EKS-LAMBDA
    type: core.Directory
    children:
    # create S3 bucket
    - name: dks-eks-ms-lambda-bucket
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: s3-bucket-dks-eks-ms-lambda
          type: aws.s3.BucketSpec
          bucketName: dks-eks-ms-lambda
          region: eu-west-3
    # upload the artifacts to S3 bucket
    - name: dks-eks-ms-lambda-artifacts
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: dks-eks-ms-lambda-artifacts
          type: aws.s3.File
          file: !file ../cloudformation/cfn-secret-provider.zip
          acl: bucket-owner-full-control
          scanPlaceholders: false
  # Provision EKS cluster using Cloudformation templates
  - name: EKS-CLOUDFORMATION
    type: core.Directory
    children:
    - name: dks-eks-ms-cloudformation-eks-user
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: dks-eks-ms-eks-user
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-user.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: dks-eks-ms
            UserStackName: dks-eks-ms-eks-user
            S3BucketPrefix: dks-eks-ms-lambda
    - name: dks-eks-ms-cloudformation-eks-vpc
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: dks-eks-ms-eks-vpc
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-vpc.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: dks-eks-ms
            VPCStackName: dks-eks-ms-eks-vpc
            AvailabilityZones: eu-west-3a, eu-west-3b
    - name: dks-eks-ms-cloudformation-eks-master
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: dks-eks-ms-eks-master
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-master.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          inputVariables:
            ProjectName: dks-eks-ms
            VPCStackName: dks-eks-ms-eks-vpc
    - name: dks-eks-ms-cloudformation-eks-workers
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: dks-eks-ms-eks-workers
          type: aws.cloudformation.Template
          file: !file ../cloudformation/eks-workers.yaml
          capabilities:
          - CAPABILITY_IAM
          - CAPABILITY_NAMED_IAM
          environmentPath: aws-eks-dks-eks-ms
          inputVariables:
            ProjectName: dks-eks-ms
            VPCStackName: dks-eks-ms-eks-vpc
            UserStackName: dks-eks-ms-eks-user
            ClusterStackName: dks-eks-ms-eks-master
            ClusterName: dks-eks-ms-master
            NodeGroupName: dks-eks-ms
        
            
    # config map used to create custom user for authentication to the EKS cluster
    - name: dks-eks-ms-k8s-configmap
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: dks-eks-ms-aws-auth
          type: k8s.ResourcesFile
          file: !file ../kubernetes/aws-auth-cm.yaml
          delimiters: "## ##"

  - name: K8S
    type: core.Directory

    children:
    # Provision K8s namespace
    - name: dks-eks-ms-namespace
      type: udm.Application
      children:
      - name: '1.0.0'
        type: udm.DeploymentPackage
        deployables:
        - name: xl-demo
          type: k8s.NamespaceSpec
          namespaceName: 'xl-demo'